#ifndef __TIMER_ID_H__
#define __TIMER_ID_H__

/* TIMER - MS */
enum
{
    TIMER_ID_COMM_EOL_RX,
    TIMER_ID_COMM_EOL_TX,

    TIMER_ID_COMM_DEBUG_RX,
    TIMER_ID_COMM_DEBUG_TX,

    TIMER_ID_COMM_FRONT_RX,
    TIMER_ID_COMM_FRONT_TX,
    TIMER_ID_COMM_FRONT_RX_ERR,
    TIMER_ID_COMM_FRONT_TX_DONE,

    TIMER_ID_COMM_TOF_RX,
    TIMER_ID_COMM_TOF_TX,
    TIMER_ID_COMM_TOF_RX_ERR,

    TIMER_ID_COMM_WAIT_1,
    TIMER_ID_COMM_WAIT_2,
    TIMER_ID_COMM_WAIT_3,
    TIMER_ID_COMM_WAIT_4,

    TIMER_ID_COMM_TX_COMPLETE_1,

    TIMER_ID_1MS,
    TIMER_ID_10MS,
    TIMER_ID_100MS,
    TIMER_ID_1SEC,
    TIMER_ID_TIME_OUT,
    TIMER_ID_FRONT,

    MAX_TIMER_ID_NUM
};

#endif /* __TIMER_ID_H__ */
